### ISSUE TITLE
Service quits as soon as I log out of SSH

### ISSUE THREAD

**Issue by Dungeonseeker** [pojntfx/bofied#14]
Running it on my Ubuntu 20.04 server which is running headless (its actually running on an old PC that's inside a cupboard in my spare room with nothing but power and Ethernet) meaning I HAVE to use SSH to control it, which is usually fine.

Installed this yesterday (full self hosted if that makes a difference) and everything is working great however as soon as I close my SSH session the service stops meaning I have to log back in and run it again then leave SSH open while I use.

I have tried enabling the service using --now to symlink it to systemd so it starts at boot up, doesn't work. I have also tried running it with &, while I get a PID for the service from this the exact same behavior happens.

This software is awesome, I was using a clunky windows based PXE and TFTP server before hand, this replaces both and assuming I can get it running all the time works better.

Is there any reason why I cannot run the service as a system service instead of a user one?

**Comment by pojntfx** [comment]
Thanks for the feedback :) You can absolutely run it as a system service, I only used a user service in the instructions because user services work without root privileges. If you want to, I can add a section on how to add it as a system service to the README. In the meantime, you can use `tmux` as workaround or create the system service manually :)

**Comment by Dungeonseeker** [comment]
Yes please, that would be awesome. I actually just used screen to achieve the same thing but since I want this running all the time I'd much rather have it running as a system service.

**Comment by pojntfx** [comment]
Just a quick update (and I realize this is coming very late) but this is fixed now: https://github.com/pojntfx/bofied?tab=readme-ov-file#4-starting-the-backend
