### ISSUE TITLE
Unable to use frontend

### ISSUE THREAD

**Issue by SR-G** [pojntfx/bofied#16]
Hello,

It should be obvious but i've tried many combinations without being able to use the frontend.
The default values + what is on the screenshot + what is described in the documentation are not in line, so it doesn't help...

I'm running the backend in a docker container on a headless server (with IP 192.168.8.139)

The backend is running with defaults, i have in the log : 

```
2021/11/07 16:58:08 bofied backend listening on :67 (DHCP), :4011 (proxyDHCP), :69 (TFTP), :15256 (WebDAV on /private, HTTP on /public and gRPC-Web on /grpc) and :15257 (gRPC), advertising IP 192.168.8.139 to DHCP clients
```

So what should i put : 
- as backend URL ? Documentation speaks about "http://" but default value at https://pojntfx.github.io/bofied/ is about ws:// + which IP / which port ?
- redirect URL ? Documentation speaks about the redirect URL previously configured ... but there is no previously configured redirect URL anywhere ... (or i missed it) ... also screenshot is about :15255

I tryed a lot of IP like : 
- backend URL : http://192.168.8.139:15256 or :15257 or same with ws://192.168.8.139:[15256|15257]
- redirect URL : http://192.168.8.139:15254 or :15255 or :15256 or :15257

So i'm quite confused : 
- is this supposed to work with another IP than localhost (instead of having everything deployed on the same local computer) ?
- what are the exact ports and protocols to be used ? (this is not obvious, per the documentation)

I'm running the container with : 

```
docker run \
    --name bofied-backend \
    -d \
    --restart always \
    --net host \
    --cap-add NET_BIND_SERVICE \
    -v /home/datas/docker-datas/bofied/:/root/.local/share/bofied:z \
    -e BOFIED_BACKEND_OIDCISSUER=https://pojntfx.eu.auth0.com/ \
    -e BOFIED_BACKEND_OIDCCLIENTID=myclientidinlowercasewithoutspecialcharacters \
    -e BOFIED_BACKEND_ADVERTISEDIP=192.168.8.139 \
    pojntfx/bofied-backend
```

Thanks in advance.

**Comment by tpickett** [comment]
it seems that the frontend is just included in the Github release as a static site. I ended up running an nginx container alongside it that downloads and extracts the frontend and deploys it alongside the backend.
The other option is to use the website they provide in the readme. it is just a PWA that uses your openid connection info and backend URI to make requests.

**Comment by pojntfx** [comment]
@tpickett Thanks for answering, I missed this issue :see_no_evil: - you're right, the frontend is distributed seperately and just a static site you can deploy to a server/CDN of your liking or use the PWA (https://pojntfx.github.io/bofied/). More info is in the README: https://github.com/pojntfx/bofied#about-the-frontend

**Comment by SR-G** [comment]
Hello,
Sorry but it's still really unclear for me.

1. About where the front-end has to be deployed - from the README.md, i understand that it is not *required* to locally host it (and that it should work with the already-deployed CDN installation). Is this correct ?
2. As described in the first message, i still have no idea about what has to be entered for the various informations - this is quite confusing inside the README.md (which ports, which protocol, ...) (again : screenshots vs text vs defaults values are never the same)

I'm really sorry but I've read many times the README and tryed many things and i'm still 100% unable to have this working.

**Comment by pojntfx** [comment]
No problems, there clearly seems to be a docs problem here :)

1) Yes! You can just open the PWA that is deployed through the CDN
2) This is always dependent on your installation. Here is mine: https://pojntfx.github.io/box/main.html#bofied - in my case, the OIDC issuer is Dex and hosted on `https://dex.jeans-box.example.com` and the backend is hosted on `https://bofied.jeans-box.example.com/`. If you want to use Dex (but you can use Auth0 etc. too), this is the setup I use: https://pojntfx.github.io/box/main.html#dex

**Comment by pojntfx** [comment]
I've rewritten the docs now to make the role of the frontend more clear: https://github.com/pojntfx/bofied?tab=readme-ov-file#frontend

Feel free to reopen if there are still issues!
